import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "./components/Header";
import Content from "./components/Content";
import Footer from "./components/Footer";
import Title from "./sections/page-2/Title";
import Search from "./sections/page-2/Search";
import Scroller from "./sections/page-2/Scroller";
import Gallery from "./sections/page-2/Gallery";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-smooth">
        <main
          className={`min-h-screen bg-[url('/forest-dark.jpg')] bg-cover bg-no-repeat`}
        >
          {/* header */}
          <Header />
          {/* content */}
          <Content />
          {/* footer */}
          <Footer />
        </main>
        {/* section 2 */}
        <section
          id="destinations"
          className="min-h-screen bg-slate-100 px-4 text-slate-700"
        >
          {/* container */}
          <div className="lg:container flex flex-col">
            {/* Title */}
            <Title />
            {/* Search */}
            <Search />
            {/* card */}
            <Gallery />
            {/* scroller */}
            <Scroller />
          </div>
        </section>
      </div>
    </>
  );
}
